language: ruby
rvm:
  - "1.9.3"
  - "2.0.0"
  - "2.1.0"
  - "2.1.1"
  - "2.1.2"
  - "2.1.3"
  - "2.1.3"
  - "2.1.4"
  - "2.1.5"
  - "2.1.6"
  - "2.2.0"
  - "2.2.1"
  - "2.2.2"
gemfile:
  - gemfiles/rails_31.gemfile
  - gemfiles/rails_32.gemfile
  - gemfiles/rails_40.gemfile
  - gemfiles/rails_41.gemfile
  - gemfiles/rails_419.gemfile
  - gemfiles/rails_42.gemfile
env:
  - DB=mysql
  - DB=postgresql
before_install:
  - gem update bundler
before_script:
  - mysql -e 'create database redirector_dummy_test; create database redirector_dummy_development;'
  - psql -c 'create database redirector_dummy_test' -U postgres
  - psql -c 'create database redirector_dummy_development' -U postgres
  - cp spec/dummy/config/database.travis.yml spec/dummy/config/database.yml
  - bundle exec rake db:migrate
matrix:
  exclude:
    - rvm: 2.2.0
      gemfile: gemfiles/rails_31.gemfile
    - rvm: 2.2.1
      gemfile: gemfiles/rails_31.gemfile
    - rvm: 2.2.2
      gemfile: gemfiles/rails_31.gemfile
    - rvm: 2.2.0
      gemfile: gemfiles/rails_32.gemfile
    - rvm: 2.2.1
      gemfile: gemfiles/rails_32.gemfile
    - rvm: 2.2.2
      gemfile: gemfiles/rails_32.gemfile
    - rvm: 2.2.0
      gemfile: gemfiles/rails_40.gemfile
    - rvm: 2.2.1
      gemfile: gemfiles/rails_40.gemfile
    - rvm: 2.2.2
      gemfile: gemfiles/rails_40.gemfile
notifications:
  slack: viget:g9nhMe2ZIu0p49xgfNQSfWxA
